# Generated by Django 3.2.5 on 2021-07-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('code', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('code', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('status change', 'Status Change'), ('new application', 'New Application'), ('issued license', 'Issued License')], default='status_change', max_length=255)),
                ('lic_num', models.IntegerField()),
                ('lic_type', models.CharField(blank=True, max_length=24)),
                ('lic_dup', models.CharField(blank=True, max_length=24)),
                ('issue_date', models.DateTimeField(blank=True)),
                ('exp_date', models.DateTimeField(blank=True)),
                ('acct_name', models.CharField(blank=True, max_length=255)),
                ('acct_own', models.CharField(blank=True, max_length=255)),
                ('acct_street', models.CharField(blank=True, max_length=255)),
                ('acct_city', models.CharField(blank=True, max_length=255)),
                ('acct_state', models.CharField(blank=True, max_length=8)),
                ('acct_zip', models.CharField(blank=True, max_length=48)),
                ('mail_street', models.CharField(blank=True, max_length=255)),
                ('mail_city', models.CharField(blank=True, max_length=255)),
                ('mail_state', models.CharField(blank=True, max_length=8)),
                ('mail_zip', models.CharField(blank=True, max_length=48)),
                ('conditions', models.CharField(blank=True, max_length=48)),
                ('escrow_addr', models.CharField(blank=True, max_length=255)),
                ('trans_from', models.CharField(blank=True, max_length=48)),
                ('trans_to', models.CharField(blank=True, max_length=48)),
                ('geocode', models.IntegerField(blank=True)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licenses.district')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licenses.status')),
                ('status_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_from', to='licenses.status')),
                ('status_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_to', to='licenses.status')),
            ],
        ),
    ]
