# Generated by Django 3.2.5 on 2021-07-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action_name',
            new_name='action_description',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_name',
            new_name='district_description',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='status_description',
        ),
    ]
