# Generated by Django 3.2.5 on 2021-07-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
