# Generated by Django 3.2.6 on 2021-08-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_report_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_type',
        ),
    ]
