# Generated by Django 3.2.5 on 2021-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20210710_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('new_application', 'New Application'), ('issued_license', 'Issued License')], default='status_change', max_length=255),
        ),
    ]
