# Generated by Django 3.2.5 on 2021-07-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_auto_20210705_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lic_num', models.IntegerField()),
                ('lic_type', models.CharField(blank=True, max_length=24)),
                ('lic_dup', models.CharField(blank=True, max_length=24)),
                ('issue_date', models.DateTimeField(blank=True)),
                ('exp_date', models.DateTimeField(blank=True)),
                ('acct_name', models.CharField(blank=True, max_length=255)),
                ('acct_own', models.CharField(blank=True, max_length=255)),
                ('acct_street', models.CharField(blank=True, max_length=255)),
                ('acct_city', models.CharField(blank=True, max_length=255)),
                ('acct_state', models.CharField(blank=True, max_length=8)),
                ('acct_zip', models.CharField(blank=True, max_length=48)),
                ('mail_street', models.CharField(blank=True, max_length=255)),
                ('mail_city', models.CharField(blank=True, max_length=255)),
                ('mail_state', models.CharField(blank=True, max_length=8)),
                ('mail_zip', models.CharField(blank=True, max_length=48)),
                ('conditions', models.CharField(blank=True, max_length=48)),
                ('escrow_addr', models.CharField(blank=True, max_length=255)),
                ('trans_from', models.CharField(blank=True, max_length=48)),
                ('trans_to', models.CharField(blank=True, max_length=48)),
                ('geocode', models.IntegerField(blank=True)),
                ('district_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licenses.district')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='licenses.status')),
                ('status_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_from', to='licenses.status')),
                ('status_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_to', to='licenses.status')),
            ],
        ),
        migrations.RemoveField(
            model_name='newapplication',
            name='action',
        ),
        migrations.RemoveField(
            model_name='newapplication',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='newapplication',
            name='status',
        ),
        migrations.RemoveField(
            model_name='statuschange',
            name='status_from',
        ),
        migrations.RemoveField(
            model_name='statuschange',
            name='status_to',
        ),
        migrations.DeleteModel(
            name='IssuedLicense',
        ),
        migrations.DeleteModel(
            name='NewApplication',
        ),
        migrations.DeleteModel(
            name='StatusChange',
        ),
    ]
