# Generated by Django 3.2.5 on 2021-07-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='in_territory',
            field=models.BooleanField(default=False),
        ),
    ]
