# Generated by Django 3.2.6 on 2021-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_remove_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('status_change', 'Status Change'), ('new_application', 'New Application'), ('issued_license', 'Issued License')], default='status_change', max_length=255),
        ),
    ]
