# Generated by Django 3.2.5 on 2021-07-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_auto_20210705_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='action_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='district_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
