# Generated by Django 3.2.5 on 2021-07-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_auto_20210705_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='username',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='recipient',
            old_name='username',
            new_name='email_address',
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('status change', 'Status Change'), ('new application', 'New Application'), ('issued license', 'Issued License')], default='status_change', max_length=255),
        ),
    ]
