# Generated by Django 3.2.6 on 2021-08-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(null=True),
        ),
    ]
