
import { Page, Report } from "./IAbcLicCheckState";

export const MenuOptions: Array<Page> = [
    {
      key: 1,
      text: "Manage Territories",
      name: "manage territories",
      type: "option",
      data: []
    },
    {
      key: 2,
      text: "Email Recipients",
      name: "email recipients",
      type: "option",
      data: []
    },
    {
      key: 3,
      text: "Download Logs",
      name: "download logs",
      type: "option",
      data: []
    },
  ];

// TODO Update headers according to report
export const Reports: Array<Report> = [    
    {
      key: 0,
      text: "Dashboard",
      name: "dashboard",
      type: "dashboard",
      data: [],
      headers: null,
    },
    {
      key: 1,
      text: "Status Changes",
      name: "status changes",
      type: "report",
      data: [],
      headers: [
        "created",
        "report_type",
        "lic_num",
        "status_from",
        "status_to",
        "lic_type",
        "lic_dup",
        "issue_date",
        "exp_date",
        "acct_name",
        "acct_own",
        "acct_street",
        "acct_city",
        "acct_state",
        "acct_zip",
        "mail_street",
        "mail_city",
        "mail_zip",
        "trans_from",
        "trans_to",
        "district",
        "geocode"
      ],
    },
    {
      key: 2,
      text: "Issued Licenses",
      name: "issued licenses",
      type: "report",
      data: [],
      headers:  [
        "created",
        "report_type",
        "lic_num",
        "status_from",
        "status_to",
        "lic_type",
        "lic_dup",
        "issue_date",
        "exp_date",
        "acct_name",
        "acct_own",
        "acct_street",
        "acct_city",
        "acct_state",
        "acct_zip",
        "mail_street",
        "mail_city",
        "mail_zip",
        "trans_from",
        "trans_to",
        "district",
        "geocode"
      ],
    },
    {
      key: 3,
      text: "New Applications",
      name: "new applications",
      type: "report",
      data: [],
      headers:  [
        "created",
        "report_type",
        "lic_num",
        "status_from",
        "status_to",
        "lic_type",
        "lic_dup",
        "issue_date",
        "exp_date",
        "acct_name",
        "acct_own",
        "acct_street",
        "acct_city",
        "acct_state",
        "acct_zip",
        "mail_street",
        "mail_city",
        "mail_zip",
        "trans_from",
        "trans_to",
        "district",
        "geocode"
      ],
    },
  ];