CREATE TABLE issued_licenses (
	lic_num VARCHAR(25) NOT NULL UNIQUE,
    created TIMESTAMP NOT NULL,
    status VARCHAR(45),
    lic_type VARCHAR(4),
    lic_dup VARCHAR(4),
    exp_date DATE,
    acct_name VARCHAR(255),
    acct_own VARCHAR(255),
    acct_street VARCHAR(255),
    acct_city VARCHAR(255),
    acct_state VARCHAR(25),
    acct_zip VARCHAR(25),
    mail_street VARCHAR(255),
    mail_city VARCHAR(255),
    mail_state VARCHAR(25),
    mail_zip VARCHAR(25),
    action VARCHAR(25),
	conditions VARCHAR(25),
    escrow VARCHAR(255),
    district_code INT,
    geo_code VARCHAR(25),
    INDEX (lic_num)
);
